Dymerz/StarCitizen-Localization

- tools/install_localization.cmd
If you have the English global.ini in the localization folder. Then this global.ini gets used. This can cause issues and so if you now choose English you use the baked-in englisch global.ini instead of ours and the g_language entire gets removed.
> Minor Fix to install_localization.cmd

- tools/ini-utils/src/commands/validate.command.ts
Fix an issue in `ini-utils` where the absence of the `=` character and its corresponding value causes the assigned value to be interpreted as a boolean rather than a string.
> Fix handling of missing `=` character and value in ini-utils

- .github/workflows/update-french.yaml
Update `peter-evans/create-pull-request` action to the `v6` tag due to GitHub API breaking changes
Fixed in [v6.0.1](https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.1)
PR: peter-evans/create-pull-request#2790
> Fix `workflows/update-french.yaml` (`Cannot read properties of undefined (reading 'number')`)

- tools/ini-utils/examples/reference.ini
- tools/ini-utils/examples/source.ini
- tools/ini-utils/src/shared/helpers/ini.helper.ts
Add the functionality to escape special characters in INI file content before parsing. This ensures that semicolons and hashes are properly handled and do not interfere with the parsing process.
#310
> Fix: Escape special characters in INI file content before parsing

- tools/ini-utils/examples/source.ini
- tools/ini-utils/src/shared/helpers/ini.helper.ts
Fixes an issue where semicolons and hash characters were being double-escaped in certain scenarios. The problem has been resolved by updating the regular expression used for escaping to exclude characters that are already escaped.
> Fix double escapement of semicolons and hash characters

- tools/ini-utils/README.md
This pull request includes a small change to the `tools/ini-utils/README.md` file. The change updates the example command to use relative paths for the INI files.
* [`tools/ini-utils/README.md`](diffhunk://#diff-ed9fb118a314394cb77f7fdac15e13d43cfcd3270c2e3d19921f5e0f641278d9L47-R47): Updated the example command to use relative paths for the INI files.
> Update file paths in validation command

- .github/workflows/update-french.yaml
This pull request includes changes to the GitHub Actions workflow for updating French localization. The most important changes involve modifying the configuration for creating pull requests.
Changes to GitHub Actions workflow:
* [`.github/workflows/update-french.yaml`](diffhunk://#diff-953feb45a476997954829d5e11b55cbbcc55a80d1af0f3802fc14bc0f487f219L57-R65): Moved the `delete-branch` setting from the `env` section to the `with` section and added a new `draft` setting to always create pull requests as drafts.
> Remove GITHUB_TOKEN and create a draft PR instead

- .github/workflows/build.yaml
Mark the workflow as a draft to prevent it from running automatically.
> Add draft flag to build workflow

- tools/install_localization.cmd
Fixed that if the user.cfg does not exist the line for example "g_language = german_(germany)" got overwritten with the line "g_languageAudio = english"
> Install localistion.cmd

- .github/workflows/validate-global-ini.yaml
This pull request includes a small change to the `.github/workflows/validate-global-ini.yaml` file. The change specifies additional pull request types to trigger the workflow.
Changes to workflow triggers:
* [`.github/workflows/validate-global-ini.yaml`](diffhunk://#diff-38b7ea30aecfc2d2077eaf8122ca44ae1a333d162939fcbe4bc18aa564db19b1R10-R14): Added `opened`, `synchronize`, `reopened`, and `ready_for_review` pull request types to the `types` section under `pull_request`.
> Update validate-global-ini.yaml workflow to trigger on pull request ready_for_review events

- tools/ini-utils/src/shared/helpers/ini.helper.ts
- tools/ini-utils/test/commands/validate-run-internal.spec.ts
- tools/ini-utils/test/fixtures/reference.ini
- tools/ini-utils/test/fixtures/source.ini
- tools/ini-utils/test/utils.ts
This pull request introduces several enhancements and bug fixes to the `IniHelper` class and its associated test suite. The changes primarily focus on improving the handling of special characters in INI files and enhancing test coverage.
* Added a new method `readFileSync` to read file content.
* Introduced a private method `escapeValues` to escape semicolons, hashes, and backslashes in INI file values.
* Modified existing tests to validate the escaping of special characters like semicolons and hashes.
* Added new test cases to cover scenarios with escaped semicolons, hashes, double semicolons, and double hashes.
* Changed test data in `reference.ini` and `source.ini` to align with the new escape logic. [[1]](diffhunk://#diff-79d53c62ef21f98fa0472c1748a200d9730bcbde1f166cdabd175a7d96bba188 …
> Fix INI file reading and escaping functionality in IniHelper class

- .github/workflows/validate-global-ini.yaml
Significant changes to the `.github/workflows/validate-global-ini.yaml` file to improve the handling of changed `global.ini` files in the GitHub Actions workflow. The changes focus on updating the method used to find and list changed files and streamlining the workflow steps.
Changes to file handling and workflow steps:
* Replaced the `tj-actions/changed-files` action with a custom script to find changed `global.ini` files using `git diff`. This change allows for more control over the file comparison process and improves the accuracy of detecting changes.
* Updated the output variable names and their references to match the new custom script's outputs (`changed_files` and `changed_files_count`).
* Added logic to determine the base and head references based on the event type (pull request, …
> Replace compromised `tj-actions/changed-files` action with custom bash script

- .github/workflows/validate-global-ini.yaml
This pull request includes a minor change to the `.github/workflows/validate-global-ini.yaml` file. The change involves modifying the syntax for passing the `changed-files` output from the `prepare` job to the `validate` script.
* [`.github/workflows/validate-global-ini.yaml`](diffhunk://#diff-38b7ea30aecfc2d2077eaf8122ca44ae1a333d162939fcbe4bc18aa564db19b1L110-R110): Corrected the syntax for the `changed-files` output in the `validate` step.
> Fix/validate global ini - validate entries

- README.md
- README_de.md
- README_es.md
- README_fr.md
- README_it.md
- README_ptbr.md
Update the French language badge across various README files to reflect the new version 4.0.2.
> Update French language badge version to 4.0.2 in multiple README files

- README.md
- README_de.md
- README_es.md
- README_fr.md
- README_it.md
- README_ptbr.md
The pull request updates the GitHub repository link for the French translation from SPEED0U/StarCitizenFrenchTranslation to SPEED0U/Scefra across multiple README files.
Fixes #457
> Update French Translation Repository Link in READMEs

- README_es.md
This pull request updates the Spanish README file (`README_es.md`) to correct encoding issues, improve formatting, and enhance clarity. The changes primarily focus on fixing character encoding problems, standardizing formatting, and ensuring proper use of Spanish diacritics and punctuation.
* Corrected character encoding issues throughout the file, such as replacing incorrectly encoded Spanish characters (e.g., "铆" → "í", "贸" → "ó") with their proper equivalents. [[1]](diffhunk://#diff-3101e8d50212e0d13a9048523bc4fd1589aad4483fce78d871aaec647fc0d863L32-R51) [[2]](diffhunk://#diff-3101e8d50212e0d13a9048523bc4fd1589aad4483fce78d871aaec647fc0d863L60-R92) [[3]](diffhunk://#diff-3101e8d50212e0d13a9048523bc4fd1589aad4483fce78d871aaec647fc0d863L102-R104) …
> fix: replace Chinese characters with Spanish

- tools/ini-utils/package-lock.json
- tools/ini-utils/package.json
- tools/ini-utils/src/shared/libs/percent-placeholder.ts
- tools/ini-utils/test/fixtures/source.ini
- tools/ini-utils/test/shared/helpers/ini-helper.spec.ts
- tools/ini-utils/test/shared/libs/percent-placeholder.spec.ts
Enhance functionality and testing in the `ini-utils` package. Key updates include adding new dependencies (`mock-fs`), improving the `PercentPlaceholder` class's comparison logic, and updating tests to reflect these changes.
* Added `mock-fs` (`^5.5.0`) and its type definitions (`@types/mock-fs` `^4.13.4`) as development dependencies in `tools/ini-utils/package.json` and `tools/ini-utils/package-lock.json`. These additions support mocking the filesystem in tests. [[1]](diffhunk://#diff-27d46e8c45101dfd45df8023eb4771a6129bd1490291dc709d675af2a66b4a13R22-R26) [[2]](diffhunk://#diff-27d46e8c45101dfd45df8023eb4771a6129bd1490291dc709d675af2a66b4a13R632-R641) [[3]](diffhunk://#diff-27d46e8c45101dfd45df8023eb4771a6129bd1490291dc709d675af2a66b4a13R2186-R2195) …
> Fix percent placeholder to handle language-specific translations

- .github/workflows/ini-utils-ci.yaml
Updates the GitHub Actions workflow configuration for `ini-utils`. The changes primarily adjust the workflow triggers and enhance the automated pull request creation process.
* Removed `.github/workflows/ini-utils-ci.yaml` from the list of paths that trigger the workflow on `pull_request` and `push` events. This prevents unnecessary workflow runs when changes are made to the workflow file itself.
* Added `draft: always-true` and assigned the pull request to `Dymerz` in the `jobs` section to improve the automation of version bump pull requests.
> fix: update CI workflow to remove unnecessary paths and add draft PR

- .github/workflows/ini-utils-ci.yaml
Updates the `.github/workflows/ini-utils-ci.yaml` file to improve version handling during the CI/CD workflow. The changes ensure that the workflow checks if a version already exists on npm before publishing or creating a pull request, thereby avoiding redundant operations.
* **Fixed version output format**: Updated the `new_version` output to exclude the `v` prefix, aligning it with npm's expected version format. (`[.github/workflows/ini-utils-ci.yamlL69-R69](diffhunk://#diff-f7d4113aba6e595fb01465655a320822f00203aebd51e4a1fa89f1df359d6ed7L69-R69)`)
* **Added npm version existence check**: Introduced a step to check if the current version of the package already exists on npm. If the version exists, the workflow skips the publish and pull request creation steps. …
> feat: add version existence check before publishing to npm

- .github/workflows/validate-global-ini.yaml
Introduces a minor update to the `.github/workflows/validate-global-ini.yaml` file to enhance error handling during the validation process.
* **Improved validation error handling**:
- Updated the `Validate key/value pairs` step to include the `--fail-on-error` flag in the `npx @dymerz/starcitizen-ini-utils validate` command. This ensures the workflow fails if any validation errors are encountered.
> feat: add --fail-on-error flag to validation command in workflow
