Dymerz/StarCitizen-Localization

README.md
Some Custom Translations
Added Missing Entries (May not be Translated!)
Hopefully fixed all "~mission(SOMETHING)" and so on
=> Updating German

tools/install_localization.cmd
=> Update English version

README_es.md
Added Spanish language in:
`./Localization/spanish_(spain)`
And README_es.md in:
`./README_es.md`
=> Added Initial spanish translate

CONTRIBUTING_it.md, README.md, README_it.md
Added instructions in Italian and added contribuing.md file in Italian
=> Added instructions in Italian

tools/install_localization.cmd
=> translation progress

.github/workflows/update-french.yaml
Yes a few of the new entries removed ",P" and now have proper text in the English file.
So I removed the ",P" and translated the entries.
=> New and modified entries translated (GER) SC 3.21.0

tools/install_localization.cmd
+ Fixed: If no "g_language" is found. Nothing happened.
+ Added ability to Remove "g_language" entry with 13.
+ Minor Clean-up
=> Fixed Some minor Issues with Installer Tool

tools/install_localization.ps1
This pull request includes the following changes:
- Update localization URL to point to the main branch.
- Refactor the language selection menu to improve user experience.
- Fix a bug in the language selection menu.
=> Update localization URL and refactor language selection menu

tools/install_localization.cmd
+ Now the Install script can download from ptu branch if in PTU folder
+ Cleanup of Install Script and more information for the user on what the script is doing
=> Added PTU Support to Install Script

.github/workflows/validate-global-ini.yaml, README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md, tools/install_localization.ps1
- Includes English, German and Brazilian
=> 3.22.0 PTU to 3.22.0 LIVE

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
No changes were found in English global.ini from the current LIVE Patch 3.22.0A-LIVE. 
Changed 3.22.0-LIVE to 3.22.0A-LIVE
=> Updated Readme´s to reflect current live Patch

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
First English changes: https://github.com/Dymerz/StarCitizen-Localization/commit/53140d42d12ca52019d9e542a55f7cb346a31635
Second English changes: https://github.com/Dymerz/StarCitizen-Localization/commit/76aeb763ab6c2b4cb2612214361a7e3a7960108b
Third English changes: https://github.com/Dymerz/StarCitizen-Localization/commit/33d2e10e10ae4a8f8862a978bff69ec534b218bb
=> German 3.23.0-ptu

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
Uploaded italian global.ini provided by https://github.com/xGattoMattox/StarCitizen-Localization/commit/d7ae9eb168fc1814133dcc6251b74878c6e39ed2#commitcomment-141715096
Fixed duplicate entries
=> Italian 3.23

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
Updated Spanish as it is now up to date #310
=> 3.23.1a-LIVE (ES_es)

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
=> Updated Readme Colors

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
English changes: https://github.com/Dymerz/StarCitizen-Localization/commit/d31dacff692ea9fbe2e719f5b95a031ea6c2604d
=> 3.24.0-ptu.9266874 (GER)

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
+ French = 3.24-LIVE
+ Fixed Contributors in pbbr
=> Updated README's

tools/ini-utils/package-lock.json, tools/ini-utils/package.json, tools/ini-utils/src/shared/helpers/string.helper.ts, tools/ini-utils/tsconfig.json
This pull request includes three commits. 
- Updates the nodemon version in the package.json file.
- Updates the target to ES2023 in the tsconfig.json file. 
- Refactors the StringHelper class to improve code readability and consistency. 
These changes enhance the overall functionality and maintainability of the codebase.
=> Update nodemon version and target to ES2023, and refactor StringHelper class

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
English changes: https://github.com/Dymerz/StarCitizen-Localization/commit/6d01367147174748360539e01b115634be52aed1
=> 3.24.2 PTU.9357571 (GER) + README's

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
English: https://github.com/Dymerz/StarCitizen-Localization/commit/306f0082e9d0e1be32a73647bdac09424a3bcf9f
=> 3.24.3-ptu.9390680 (GER)

tools/install_localization.ps1
Fix folder navigation and minor cleanup
=> Remove unnecessary folder navigation in install_localization.ps1

tools/ini-utils/package-lock.json, tools/ini-utils/package.json
This pull request includes updates to various dependencies and devDependencies in the `tools/ini-utils` package. The changes involve updating the versions of several packages to their latest releases.
Dependency updates:
* Updated `@types/ini` from `^1.3.31` to `^4.1.1` and `ini` from `^4.1.1` to `^5.0.0`. [[1]](diffhunk://#diff-27d46e8c45101dfd45df8023eb4771a6129bd1490291dc709d675af2a66b4a13L12-R23) [[2]](diffhunk://#diff-27d46e8c45101dfd45df8023eb4771a6129bd1490291dc709d675af2a66b4a13L610-R612) [[3]](diffhunk://#diff-27d46e8c45101dfd45df8023eb4771a6129bd1490291dc709d675af2a66b4a13L1629-R1645) [[4]](diffhunk://#diff-9b401a6af5afa049258267891f273711fdc362093ccfc42e65b2992c813d5949L20-R31)
* Updated `@types/node` from `^20.8.6` to `^22.13.0`. …
=> [tools/ini-utils] Update dependencies in package.json

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
English changes: 
1. https://github.com/Dymerz/StarCitizen-Localization/commit/ff558b77da026f13b923a3c54dcfaf38ad3c2585
2. https://github.com/Dymerz/StarCitizen-Localization/commit/48262d3595a156e6e3e465fb2ce39b37d68857f8
=> 4.0.2-PTU.9518844 + 4.0.2-ptu.9521869 (GER)

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
Update the French localization across multiple language files to reflect the latest version 4.0.2.
#444
=> Update French localization to version 4.0.2

.github/workflows/validate-global-ini.yaml, README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
English: https://github.com/Dymerz/StarCitizen-Localization/commit/f3e638a6e407b8c103d7406415cb0b244512a5df
=> 4.1.0-PTU.9622512 (GER) + 4.1.0-PTU.9627438 (GER)

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md, tools/install_localization.i18n.json, tools/install_localization.ps1
Update installation instructions for PowerShell to streamline the process. Fix newline characters in interactive menu hints across multiple languages. Refactor exit calls to return statements for better function flow in the localization script, and enhance the Get-Translate function to provide a fallback key for missing locales.
=> Simplify installation instructions and enhance localization handling

README.md, README_de.md, README_es.md, README_fr.md, README_it.md, README_ptbr.md
Fix formatting in localization README files for consistency
=> Fix formatting in localization README files for consistency

tools/ini-utils/README.md, tools/ini-utils/package-lock.json, tools/ini-utils/package.json, tools/ini-utils/src/commands/validate.command.ts, tools/ini-utils/src/index.ts, tools/ini-utils/src/shared/strategies/ci-output-strategy.ts, tools/ini-utils/src/shared/strategies/index.ts, tools/ini-utils/src/shared/strategies/output-strategy-factory.ts, tools/ini-utils/src/shared/strategies/output-strategy.ts, tools/ini-utils/src/shared/strategies/standard-output-strategy.ts, tools/ini-utils/test/commands/validate-run-internal.spec.ts, tools/ini-utils/test/shared/strategies/output-strategies.spec.ts, tools/ini-utils/test/shared/strategies/output-strategy-factory.spec.ts
Introduces a significant update to the `@dymerz/starcitizen-ini-utils` tool, focusing on enhancing CI mode functionality, improving output formatting, and refactoring the validation process for better extensibility and maintainability. The most important changes include the addition of a CI-friendly output strategy, updates to the `ValidateCommand` class to support multiple output strategies, and modifications to the test suite to align with the new validation logic.
* Updated the `--ci` flag to include GitHub Actions annotations, machine-readable output, and non-zero exit codes for validation failures. Documentation was updated to reflect these changes (`tools/ini-utils/README.md`). [[1]](diffhunk://#diff-ed9fb118a314394cb77f7fdac15e13d43cfcd3270c2e3d19921f5e0f641278d9L89-R99) …
=> Feature/ini utils GitHub output
